Python1811/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^axf/', include('app.urls',namespace='axf'))
]

app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r"^$",views.home,name='index'),

    url(r'^home/$',views.home,name='home'),

    url(r'^market/$', views.market, name='market'),

    url(r'^cart/$',views.cart,name='cart'),

    url(r'^mine/$',views.mine,name='mine'),


]

app/models.py
from django.db import models

# 基础类
class Base(models.Model):
    img = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    trackid = models.CharField(max_length=8)

    class Meta:
        abstract = True

# 轮播图  模型类
class Wheel(Base):
    class Meta:
        db_table = 'axf_wheel'

# 导航  模型类
class Nav(Base):
    class Meta:
        db_table = 'axf_nav'

# 每日必购  模型类
class Mustbuy(Base):
    class Meta:
        db_table = 'axf_mustbuy'

# 商品  模型类
class Shop(Base):
    class Meta:
        db_table='axf_shop'


# 商品主体
class MainShow(models.Model):
    trackid = models.CharField(max_length=10)
    name = models.CharField(max_length=100)
    img = models.CharField(max_length=200)
    categoryid = models.CharField(max_length=10)
    brandname = models.CharField(max_length=50)

    img1 = models.CharField(max_length=200)
    childcid1 = models.CharField(max_length=10)
    productid1 = models.CharField(max_length=10)
    longname1 = models.CharField(max_length=200)
    price1 = models.FloatField()
    marketprice1 = models.FloatField()

    img2 = models.CharField(max_length=200)
    childcid2 = models.CharField(max_length=10)
    productid2 = models.CharField(max_length=10)
    longname2 = models.CharField(max_length=200)
    price2 = models.FloatField()
    marketprice2 = models.FloatField()

    img3 = models.CharField(max_length=200)
    childcid3 = models.CharField(max_length=10)
    productid3 = models.CharField(max_length=10)
    longname3 = models.CharField(max_length=200)
    price3 = models.FloatField()
    marketprice3 = models.FloatField()

    class Meta:
        db_table = 'axf_mainshow'


    # 商品类型
class Foodtype(models.Model):
    #分类id
    typeid = models.CharField(max_length=10)
    #分类名字
    typename = models.CharField(max_length=100)
    # 子类名字
    childtypenames = models.CharField(max_length=200)
    # 分类排序
    typesort = models.IntegerField()

    class Meta:
        db_table = 'axf_foodtypes'



    # 商品模型类
class Goods(models.Model):
    # 商品ID
    productid = models.CharField(max_length=10)
    # 商品图片
    productimg = models.CharField(max_length=200)
    # 商品名称
    productname = models.CharField(max_length=100)
    # 商品长名字
    productlongname = models.CharField(max_length=200)
    # 精选
    isxf = models.BooleanField(default=False)
    # 买一送一
    pmdesc = models.BooleanField(default=False)
    # 规格
    specifics = models.CharField(max_length=100)
    # 价格
    price = models.DecimalField(max_digits=8,decimal_places=2)
    # 超市价格
    marketprice = models.DecimalField(max_digits=8,decimal_places=2)
    # 分类ID
    categoryid = models.IntegerField()
    # 子类ID
    childcid = models.IntegerField()
    # 子类名字
    childcidname = models.CharField(max_length=100)
    # 详情id
    dealerid = models.CharField(max_length=100)
    # 库存量
    storenums = models.IntegerField()
    # 销售量
    productnum = models.IntegerField()

    class Meta:
        db_table = 'axf_goods'

app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from app.models import Wheel, Nav, Mustbuy, Shop, MainShow, Foodtype, Goods


def home(request):
    #轮播图数据
    wheels = Wheel.objects.all()

    #导航数据
    navs = Nav.objects.all()

    # 每日必购
    mustbuys = Mustbuy.objects.all()


    # 商品（部分）
    shops =Shop.objects.all()
    shophead =shops[0]
    shoptabs = shops[1:3]
    shopclass = shops[3:7]
    shopcommends =shops[7:11]

    # 商品主体
    mainshows = MainShow.objects.all()

    data = {
        'wheels':wheels,
        'navs':navs,
        'mustbuys':mustbuys,
        'shophead':shophead,
        'shoptabs':shoptabs,
        'shopclass':shopclass,
        'shopcommends':shopcommends,
        'mainshows':mainshows,
    }
    return render(request,'home/home.html',context=data)


def market(request):
    # 分类
    foodtypes = Foodtype.objects.all()

    # 获取 客户端点击的 分类下标  ==》》typeIndex
    typeIndex = int(request.COOKIES.get('typeIndex',0))

    # 根据分类下标   获取 分类ID
    categoryid = foodtypes[typeIndex].typeid

    # 获取对应分类下 子类
    childtypenames = foodtypes[typeIndex].childtypenames
    # 拆分
    childtypes = []
    for item in childtypenames.split('#'):
        # item  >> 子类名称:子类ID
        temp = item.split(':')
        dir = {
            'childname': temp[0],
            'childid': temp[1]
        }
        childtypes.append(dir)

    # 商品
    # goods_list = Goods.objects.all()[0:5]
    goods_list = Goods.objects.filter(categoryid=categoryid)


    data = {
        'foodtypes':foodtypes,
        'goods_list':goods_list,
        'childtypes':childtypes,

    }
    return render(request, 'market/market.html',context=data)


def cart(request):
    return render(request, 'cart/cart.html')


def mine(request):
    return render(request, 'mine/mine.html')


def marketbase(request):
    return redirect('axf:market')

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">

    {% block extbasecss %}
    {% endblock %}
</head>
<body>

{% block body %}

{% endblock %}

{#<scirpt src="{% static 'base/js/jquery.min.js' %}"></scirpt>#}
{#<scirpt src="{% static 'base/js/jquery.js' %}"></scirpt>#}
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
<script src="{% static 'base/js/base.js' %}"></script>
<scirpt src="{% static 'base/js/bootstrap.min.js' %}"></scirpt>
{% block extbasejs %}
{% endblock %}
</body>
</html>

templates/base/base_h_f.html
{% extends 'base/base.html' %}
{% load static %}

{% block extbasecss %}
    <link rel="stylesheet" href="{% static 'base/css/base_h_f.css' %}">
    {% block extcss %}
    {% endblock %}
{% endblock %}

{% block extbasejs %}
    <script src="{% static 'base/js/base_h_f.js' %}"></script>
    {% block extjs %}
    {% endblock %}
{% endblock %}

{% block body %}
{#    头部#}
    {% block header %}
        <header>爱鲜蜂</header>
    {% endblock %}

{#    主体内容#}
    <div class="hidescroll">
        <div id="content">
            {% block content %}

            {% endblock %}
        </div>
    </div>

{#    尾部#}
    {% block footer %}
        <footer>
            <a href="{% url 'axf:home' %}" class="home">
                <dl>
                    <dt> <span></span> </dt>
                    <dd>首页</dd>
                </dl>
            </a>
            <a href="{% url 'axf:market'  %}" class="market">
                <dl>
                    <dt> <span></span> </dt>
                    <dd>闪购超市</dd>
                </dl>
            </a>
            <a href="{% url 'axf:cart' %}" class="cart">
                <dl>
                    <dt> <span></span> </dt>
                    <dd>购物车</dd>
                </dl>
            </a>
            <a href="{% url 'axf:mine' %}" class="mine">
                <dl>
                    <dt> <span></span> </dt>
                    <dd>我的</dd>
                </dl>
            </a>
        </footer>
    {% endblock %}
{% endblock %}

templates/cart/cart.html
{% extends 'base/base_h_f.html' %}
{% load static %}

{% block title %}
    爱鲜蜂 | 购物车
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'cart/js/cart.js' %}"></script>
{% endblock %}

{% block content %}
    <h1>购物车</h1>
{% endblock %}

templates/home/home.html
{% extends 'base/base_h_f.html' %}
{% load static %}

{% block title %}
    爱鲜蜂 | 首页
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'home/css/swiper.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'home/js/swiper.jquery.min.js' %}"></script>
    <script src="{% static 'home/js/home.js' %}"></script>
{% endblock %}

{% block content %}
<div class="home">
{#    轮播图#}
    <div class="swiper-container" id="topSwiper">
        <div class="swiper-wrapper">
            {% for wheel in wheels %}
                <div class="swiper-slide">
                    <img src="{{ wheel.img }}" alt="">
                </div>
            {% endfor %}
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>
    </div>

{#    导航#}
    <div class="nav">
        <ul>
            {% for nav in navs %}
                <li>
                    <img src="{{ nav.img }}" alt="">
                    <span>{{ nav.name }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>


{#    每日必购#}
    <div class="swiper-container" id="mustbuySwiper">
        <div class="swiper-wrapper">
            {% for mustbuy in mustbuys %}
                <div class="swiper-slide">
                    <img src="{{ mustbuy.img }}" alt="">
                </div>
            {% endfor %}
        </div>
    </div>

{#    商品(部分)#}
    <div class="shop">
        <div class="shophead">
            <a href="#">
                <img src="{{ shophead.img }}" alt="">
            </a>
        </div>
        <div class="shoptab">
            {% for shoptab in shoptabs %}
                <a href="#">
                    <img src="{{ shoptab.img }}" alt="">
                </a>
            {% endfor %}
        </div>
        <ul class="shopclass">
            {% for item in shopclass %}
                <li>
                    <a href="#">
                        <img src="{{ item.img }}" alt="">
                    </a>
                </li>
            {% endfor %}
        </ul>
        <ul class="shopcommend">
            {% for shopcommend in shopcommends %}
                <li>
                    <a href="#">
                        <img src="{{ shopcommend.img }}" alt="">
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>

{#   商品主体内容#}
    <div class="main">
        {% for mainshow in mainshows %}
            <div class="main-wrapper">
                <div class="title">
                    {{ mainshow.name }}
                    <a href="#">更多</a>
                    <span></span>
                </div>
                <div class="headimg">
                    <img src="{{ mainshow.img }}" alt="">
                </div>
                <div class="shoplist">
                    <div class="shopitem">
                        <a href="#">
                            <img class="img" src="{{ mainshow.img1 }}" alt="">
                            <p class="desc">{{ mainshow.longname1 }}</p>
                            <span class="price">￥{{ mainshow.price1 }}</span>
                            <span class="marketprice">￥{{ mainshow.marketprice1 }}</span>
                        </a>
                        <button>+</button>
                    </div>
                    <div class="shopitem">
                        <a href="#">
                            <img class="img" src="{{ mainshow.img2 }}" alt="">
                            <p class="desc">{{ mainshow.longname2 }}</p>
                            <span class="price">￥{{ mainshow.price2 }}</span>
                            <span class="marketprice">￥{{ mainshow.marketprice2 }}</span>
                        </a>
                        <button>+</button>
                    </div>
                    <div class="shopitem">
                        <a href="#">
                            <img class="img" src="{{ mainshow.img3 }}" alt="">
                            <p class="desc">{{ mainshow.longname3}}</p>
                            <span class="price">￥{{ mainshow.price3 }}</span>
                            <span class="marketprice">￥{{ mainshow.marketprice3 }}</span>
                        </a>
                        <button>+</button>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/market/market.html
{% extends 'base/base_h_f.html' %}
{% load static %}

{% block title %}
    爱鲜蜂 | 闪购超市
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'market/js/jquery.cookie.js' %}"></script>
    <script src="{% static 'market/js/market.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="market">
{#      侧边栏(分类)#}
        <div class="type-slider">
            <ul>
                {% for foodtype in foodtypes %}
                <li class="type-item">
                    <a href="{% url 'axf:market' %}">
                        <span></span>
                        {{ foodtype.typename }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>

{#      顶部(子类、排序)#}
        <nav>
            <ul>
                <li id="category-bt">
                    <span>
                        全部类型
                        <i class="glyphicon glyphicon-triangle-top"></i>
                    </span>
                </li>
                <li id="sort-bt">
                    <span>
                        综合排序
                        <i class="glyphicon glyphicon-triangle-top "></i>
                    </span>
                </li>
            </ul>
        </nav>

{#      主体内容#}
        <div class="main-content">
{#            商品信息#}
            <div class="content-wrapper">
                <ul>
                    {% for goods in goods_list %}
                    <li>
                        <a href="#">
                            <img class="goods-img" src="{{ goods.productimg }}" alt="">
                            <div class="goods-info">
                                <p class="name">
                                    {{ goods.productlongname }}
                                </p>
                                <p class="detailtag">
                                    {% if goods.isxf %}
                                        <span class="xf">精选</span>
                                    {% endif %}
                                    销量: {{ goods.productnum }}
                                </p>
                                <p class="specifics">
                                    {{ goods.specifics }}
                                </p>
                                <p class="price">
                                    <span class="now-price">{{ goods.price }}</span>
                                    <span class="market-price">{{ goods.marketprice }}</span>
                                </p>
                            </div>
                        </a>

                        <div class="bt-wrapper">
                            <span class="glyphicon glyphicon-minus"></span>
                            <span class="num">10</span>
                            <span class="glyphicon glyphicon-plus"></span>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>

{#            子类#}
            <div class="bounce-view category-view">
                <div class="bounce-wrapper">
                    {% for childtype in childtypes %}
                        <a href="#">
                            {{ childtype.childname }}
                        </a>
                    {% endfor %}
                </div>
            </div>

{#            排序#}
            <div class="bounce-view sort-view">
                <div class="bounce-wrapper">
                    <a href="#">综合排序</a>
                    <a href="#">销量排序</a>
                    <a href="#">价格最低</a>
                    <a href="#">价格最高</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/mine/mine.html
{% extends 'base/base_h_f.html' %}
{% load static %}

{% block title %}
    爱鲜蜂 | 我的
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}
    <h1>我的</h1>
{% endblock %}